version: "3.4"
services:
  app:
    image: namtechdocker/reactjs-database-report:1.1.0
    volumes:
      - ./configs/logs:/app/configs/logs

    ports:
      - "1998:1998"
      - "1999:1999"
    restart: always